Repository openshift/okd-machine-os, pull requests merged in 2020-12, with the labels that each got.

#20 overlay: add custom /etc/nsswitch.conf
  overlay/etc/nsswitch.conf
Labels: approved, lgtm

#19 Add files to be reused by installer
  Dockerfile
  bootstrap/manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml
  bootstrap/manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
  bootstrap/manifests/99-okd-community-operators.yaml
  bootstrap/manifests/99-okd-master-disable-mitigations.yaml
  bootstrap/manifests/99-okd-worker-disable-mitigations.yaml
  bootstrap/overlay/etc/pivot/kernel-args
  bootstrap/overlay/etc/systemd/system/openshift-gcp-routes.service
  bootstrap/overlay/etc/zincati/config.d/90-disable-feature.toml
  bootstrap/overlay/usr/local/bin/openshift-gcp-routes.sh
Labels: approved, lgtm

#23 Add usbguard and kernel-devel RPMs to extensions yum repo
  entrypoint.sh
Labels: approved, lgtm

#21 overlay: run gcp-hostname on GCP only
  overlay/etc/systemd/system/gcp-hostname.service
Labels: approved, lgtm

#24 overlay: Disable zincati.service via dropin
  bootstrap/overlay/etc/systemd/system/zincati.service.d/okd-machine-os-disabled.conf
  bootstrap/overlay/etc/zincati/config.d/90-disable-feature.toml
Labels: approved, lgtm

#27 Update a list of vendored RPMs
  entrypoint.sh
Labels: approved, lgtm

#18 Add qemu-guest-agent RPM to extensions
  bootstrap/manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml
  bootstrap/manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
  entrypoint.sh
  manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml
  manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
Labels: approved, lgtm

#31 overlay: set vSphere hostname fetched from Afterburn
  overlay/etc/systemd/system/network-online.target.wants/vsphere-hostname.service
Labels: approved, lgtm

#36 bootstrap: install open-vm-tools binaries from RPMs
  bootstrap/overlay/etc/systemd/system/multi-user.target.wants/openshift-gcp-routes.service
  bootstrap/overlay/etc/systemd/system/multi-user.target.wants/vmtoolsd.service
  entrypoint.sh
Labels: approved, lgtm

#40 Dockerfile: use stable cosa
  Dockerfile
Labels: approved, lgtm

#35 bootstrap: add pre-pivot.sh
  bootstrap/pre-pivot.sh
Labels: approved, lgtm

#44 Add kernel-headers to internal repo
  entrypoint.sh
Labels: approved, bugzilla/valid-bug, lgtm

#42 Fail the build if kubelet isn't labeled correctly
  entrypoint.sh
Labels: approved, bugzilla/valid-bug, lgtm

#49 [4.6] Pin FCOS to 33.20201209.10.0
  entrypoint.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#50 Pin FCOS to 33.20201209.10.0
  entrypoint.sh
Labels: approved, bugzilla/valid-bug, lgtm

#48 Remove `vsphere-hostname`
  overlay/etc/systemd/system/network-online.target.wants/vsphere-hostname.service
Labels: approved, bugzilla/valid-bug, lgtm

#46 [4.6] revert systemd-resolved tweaks
  overlay/etc/nsswitch.conf
  overlay/etc/systemd/resolved.conf.d/no-dns-stub.conf
  overlay/etc/systemd/system/coreos-migrate-to-systemd-resolved.service.d/disabled.conf
Labels: approved, lgtm

#47 Remove systemd-resolved workarounds
  overlay/etc/nsswitch.conf
  overlay/etc/systemd/resolved.conf.d/no-dns-stub.conf
  overlay/etc/systemd/system/coreos-migrate-to-systemd-resolved.service.d/disabled.conf
Labels: approved, lgtm

#51 [4.6] Use FCOS stable stream
  entrypoint.sh
Labels: approved, cherry-pick-approved, lgtm

#52 Symlink resolv.conf to /run/systemd/resolve/resolv.conf
  entrypoint.sh
  overlay/etc/resolv.conf
  overlay/etc/systemd/resolved.conf.d/no-dns-stub.conf
Labels: approved, lgtm

#53 [4.6] Symlink resolv.conf to /run/systemd/resolve/resolv.conf
  overlay/etc/resolv.conf
  overlay/etc/systemd/resolved.conf.d/no-dns-stub.conf
Labels: approved, lgtm
